# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  mazurel.username = "mateusz";
  mazurel.languages.polish.enable = true;

  mazurel.xorg.des.gnome.enable = true;
  # mazurel.xorg.des.cinnamon.enable = true;

  # services.tlp.enable = true;
  powerManagement.enable = true;
  # services.upower.enable = true;
  # programs.qt5ct.enable = lib.mkForce false;

  mazurel.development.emacs.enable = true;
  mazurel.development.emacs.defaultEditor = true;

  mazurel.development.cuda.enable = true;

  mazurel.virtualization = {
    enable = false;
    # Devices that will be disabled and ready for passthorugh
    # Remember to disable gpu in bios (change display)

    # Needed if acs are not valid
    acs-override-patch = false;
  };

  hardware.opengl.enable = true;
  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
  hardware.nvidia.modesetting.enable = true;

  users.users.mateusz.extraGroups = [
    "video"
  ];

  boot.blacklistedKernelModules = [
    "nouveau"
  ];

  nix.maxJobs = 8;

  # Network settings
  networking = {
    hostName = "Nixos-laptop";

    networkmanager.enable = true;
  };

  # Make CPU speed as fast as possible
  powerManagement.cpuFreqGovernor = "performance";

  environment.systemPackages = [
    (
      pkgs.writeShellScriptBin "nvidia-offload" ''
        export __NV_PRIME_RENDER_OFFLOAD=1
        export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
        export __GLX_VENDOR_LIBRARY_NAME=nvidia
        export __VK_LAYER_NV_optimus=NVIDIA_only
        exec -a "$0" "$@"
      ''
    )
  ];

  services.xserver = {
    videoDrivers = [ "nvidia" ];
    libinput.enable = true; # Touchpad
    #displayManager.lightdm.enable = true;
    #displayManager.gdm.enable = lib.mkForce false;
  };

  services.xserver.screenSection = ''
    Option    "Xinerama" "false"
  '';


  hardware.nvidia.prime = {
    offload.enable = true;

    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:3:0:0";
  };

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernelPackages = pkgs.linuxPackages_zen;

  boot.loader = {
    grub = {
      enable = true;
      version = 2;

      # Efi config
      efiSupport = true;
      efiInstallAsRemovable = false;
      device = "nodev";

      enableCryptodisk = true;

      extraEntries = ''
        menuentry "UEFI Settings" {
        fwsetup
        }
      '';
    };

    efi.efiSysMountPoint = "/boot";
    efi.canTouchEfiVariables = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/NixStore";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/Home";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypted_sda4".device =
    "/dev/disk/by-uuid/3589cda3-abfc-47ec-b832-663951cc318e";
  boot.initrd.luks.devices."crypted_sda4".preLVM = true;

  swapDevices = [ ];
}
