# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  mazurel.username = "mateusz";
  mazurel.languages.polish.enable = true;

  mazurel.xorg.des.gnome.enable = true;
  mazurel.development.emacs.enable = true;
  mazurel.development.emacs.defaultEditor = true;

  mazurel.virtualization = {
    enable = false;
    # Devices that will be disabled and ready for passthorugh
    # Remember to disable gpu in bios (change display)

    # Needed if acs are not valid
    acs-override-patch = false;
  };

  nix.maxJobs = 8;

  # Network settings
  networking = {
    hostName = "Nixos-laptop";

    networkmanager.enable = true;
  };

  # Make CPU speed as fast as possible
  powerManagement.cpuFreqGovernor = "performance";

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernelPackages = pkgs.linuxPackages_zen;

  boot.loader = {
    grub = {
      enable = true;
      version = 2;

      # Efi config
      efiSupport = true;
      efiInstallAsRemovable = false;
      device = "nodev";

      enableCryptodisk = true;
    };

    efi.efiSysMountPoint = "/boot";
    efi.canTouchEfiVariables = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/NixStore";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/Home";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypted_sda4".device =
    "/dev/disk/by-uuid/3589cda3-abfc-47ec-b832-663951cc318e";
  boot.initrd.luks.devices."crypted_sda4".preLVM = true;

  swapDevices = [ ];
}
